/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Ingredient, MenuItem, CustomerAccount, PromotionNotification, Order, UserRole, OrderStatus, PaymentMethod, PaymentStatus, MembershipTier } from './types';

export const INITIAL_INGREDIENTS: Ingredient[] = [
  { id: 'tea_black', name: 'Trà Đen Phúc Bồn', currentStock: 9500, minStock: 2000, unit: 'g', unitCost: 350 },
  { id: 'tea_oolong', name: 'Trà Oolong Đặc Sản', currentStock: 8500, minStock: 2000, unit: 'g', unitCost: 450 },
  { id: 'tea_thai', name: 'Lá Trà Thái Xanh', currentStock: 6000, minStock: 1500, unit: 'g', unitCost: 400 },
  { id: 'tea_matcha', name: 'Bột Matcha Nhật', currentStock: 4200, minStock: 1000, unit: 'g', unitCost: 750 },
  { id: 'fresh_fruit_mango', name: 'Xoài Cát Tươi', currentStock: 15000, minStock: 3000, unit: 'g', unitCost: 150 },
  { id: 'fresh_fruit_passion', name: 'Chanh Dây Tươi', currentStock: 12000, minStock: 2000, unit: 'g', unitCost: 180 },
  { id: 'fresh_fruit_guava', name: 'Ổi Hồng Rừng', currentStock: 8000, minStock: 2000, unit: 'g', unitCost: 160 },
  { id: 'fresh_fruit_pineapple', name: 'Thơm (Dứa) Mật', currentStock: 10000, minStock: 2000, unit: 'g', unitCost: 120 },
  { id: 'fresh_fruit_peach', name: 'Đào Miếng Ngâm', currentStock: 5000, minStock: 1000, unit: 'g', unitCost: 200 },
  { id: 'milk_powder', name: 'Bột Sữa Kem Béo', currentStock: 18000, minStock: 4000, unit: 'g', unitCost: 280 },
  { id: 'sugar_syrup', name: 'Đường Nước Tự Nhiên', currentStock: 22000, minStock: 4000, unit: 'ml', unitCost: 90 },
  { id: 'packaging_cup', name: 'Ly Nhựa Sinh Học 500ml', currentStock: 1200, minStock: 200, unit: 'cái', unitCost: 1000 },
  { id: 'packaging_straw', name: 'Ống Hút Trân Châu', currentStock: 1500, minStock: 200, unit: 'cái', unitCost: 200 },
];

export const INITIAL_MENU: MenuItem[] = [
  // --- NHÓM 1: TRÀ TRÁI CÂY (Fruit Tea) ---
  {
    id: 'm_xoai_chanhday',
    name: 'Trà Xoài + Chanh Dây',
    price: 20000,
    category: 'Trà Trái Cây',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=400',
    description: 'Xoài chín dẻo ngọt ngào phối hợp cùng nước cốt chanh dây thơm lừng, chua ngọt thanh mát.',
    available: true,
    recipe: [
      { ingredientId: 'tea_oolong', amount: 10 },
      { ingredientId: 'fresh_fruit_mango', amount: 40 },
      { ingredientId: 'fresh_fruit_passion', amount: 30 },
      { ingredientId: 'sugar_syrup', amount: 25 },
      { ingredientId: 'packaging_cup', amount: 1 },
      { ingredientId: 'packaging_straw', amount: 1 },
    ],
  },
  {
    id: 'm_oi_chanhday',
    name: 'Trà Ổi Hồng + Chanh Dây',
    price: 18000,
    category: 'Trà Trái Cây',
    imageUrl: 'https://images.unsplash.com/photo-1546173152-318ae14d43e4?auto=format&fit=crop&q=80&w=400',
    description: 'Ổi hồng thơm dịu dàng bổ dưỡng kết hợp chanh dây thanh mát, giàu Vitamin C.',
    available: true,
    recipe: [
      { ingredientId: 'tea_oolong', amount: 10 },
      { ingredientId: 'fresh_fruit_guava', amount: 40 },
      { ingredientId: 'fresh_fruit_passion', amount: 20 },
      { ingredientId: 'sugar_syrup', amount: 20 },
      { ingredientId: 'packaging_cup', amount: 1 },
      { ingredientId: 'packaging_straw', amount: 1 },
    ],
  },
  {
    id: 'm_thom_chanhday',
    name: 'Trà Thơm (Dứa) + Chanh Dây',
    price: 18000,
    category: 'Trà Trái Cây',
    imageUrl: 'https://images.unsplash.com/photo-1497534446932-c925b458314e?auto=format&fit=crop&q=80&w=400',
    description: 'Vị dứa chín ngọt mật dạt dào sảng khoái đan xen chanh dây tươi dào dạt sảng khoái.',
    available: true,
    recipe: [
      { ingredientId: 'tea_oolong', amount: 10 },
      { ingredientId: 'fresh_fruit_pineapple', amount: 45 },
      { ingredientId: 'fresh_fruit_passion', amount: 20 },
      { ingredientId: 'sugar_syrup', amount: 20 },
      { ingredientId: 'packaging_cup', amount: 1 },
      { ingredientId: 'packaging_straw', amount: 1 },
    ],
  },
  {
    id: 'm_dua_mangcau',
    name: 'Trà Dứa Lưới + Mãng Cầu',
    price: 18000,
    category: 'Trà Trái Cây',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=400',
    description: 'Dứa lưới căng mọng ngát hương kết hợp mãng cầu xiêm ngọt bùi đặc sản chua ngọt dẻo dòn.',
    available: true,
    recipe: [
      { ingredientId: 'tea_oolong', amount: 10 },
      { ingredientId: 'fresh_fruit_pineapple', amount: 30 },
      { ingredientId: 'sugar_syrup', amount: 25 },
      { ingredientId: 'packaging_cup', amount: 1 },
      { ingredientId: 'packaging_straw', amount: 1 },
    ],
  },
  {
    id: 'm_dau_dautam',
    name: 'Trà Dâu Tây + Dâu Tằm',
    price: 18000,
    category: 'Trà Trái Cây',
    imageUrl: 'https://images.unsplash.com/photo-1546173152-318ae14d43e4?auto=format&fit=crop&q=80&w=400',
    description: 'Trà Oolong thơm dịu kết hợp dâu tây dạt dào cùng mứt dâu tằm đỏ ngọc ngọt thanh cuốn hút.',
    available: true,
    recipe: [
      { ingredientId: 'tea_oolong', amount: 10 },
      { ingredientId: 'sugar_syrup', amount: 20 },
      { ingredientId: 'packaging_cup', amount: 1 },
      { ingredientId: 'packaging_straw', amount: 1 },
    ],
  },
  {
    id: 'm_atiso_combo',
    name: 'Trà Atiso + Đào + Vải + Mận',
    price: 18000,
    category: 'Trà Trái Cây',
    imageUrl: 'https://images.unsplash.com/photo-1497534446932-c925b458314e?auto=format&fit=crop&q=80&w=400',
    description: 'Thanh lọc cơ thể hoàn hảo với cốt trà Atiso đỏ, đào giòn giòn, vải thiều ngọt bùi cùng mứt mận dẻo thơm.',
    available: true,
    recipe: [
      { ingredientId: 'tea_black', amount: 12 },
      { ingredientId: 'fresh_fruit_peach', amount: 20 },
      { ingredientId: 'sugar_syrup', amount: 22 },
      { ingredientId: 'packaging_cup', amount: 1 },
      { ingredientId: 'packaging_straw', amount: 1 },
    ],
  },
  {
    id: 'm_que_hoa',
    name: 'Trà Quế Hoa Đặc Biệt',
    price: 15000,
    category: 'Trà Trái Cây',
    imageUrl: 'https://images.unsplash.com/photo-1497534446932-c925b458314e?auto=format&fit=crop&q=80&w=400',
    description: 'Trà ướp quế hoa thanh khiết, ngát hương quế tự nhiên dịu ngọt giúp giảm stress, ngủ ngon giấc.',
    available: true,
    recipe: [
      { ingredientId: 'tea_oolong', amount: 15 },
      { ingredientId: 'sugar_syrup', amount: 15 },
      { ingredientId: 'packaging_cup', amount: 1 },
      { ingredientId: 'packaging_straw', amount: 1 },
    ],
  },

  // --- NHÓM 2: TRÀ TRÁI CÂY NHIỆT ĐỚI (Tropical Fruit Tea) ---
  {
    id: 'm_dao_camsa',
    name: 'Trà Đào Cam Sả',
    price: 20000,
    category: 'Trà Trái Cây Nhiệt Đới',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=400',
    description: 'Sự hòa quyện kinh điển giữa đào ngâm lát giòn, cam tươi ngát hương cùng một chút sả ấm nồng.',
    available: true,
    recipe: [
      { ingredientId: 'tea_black', amount: 12 },
      { ingredientId: 'fresh_fruit_peach', amount: 35 },
      { ingredientId: 'sugar_syrup', amount: 25 },
      { ingredientId: 'packaging_cup', amount: 1 },
      { ingredientId: 'packaging_straw', amount: 1 },
    ],
  },
  {
    id: 'm_vai_thanhlong',
    name: 'Trà Vải Thanh Long',
    price: 20000,
    category: 'Trà Trái Cây Nhiệt Đới',
    imageUrl: 'https://images.unsplash.com/photo-1546173152-318ae14d43e4?auto=format&fit=crop&q=80&w=400',
    description: 'Ly trà rực rỡ sắc đỏ thanh long tươi nguyên bản quyện cùng những trái vải ngâm trọn vẹn dên dẻ dòn sần sật.',
    available: true,
    recipe: [
      { ingredientId: 'tea_black', amount: 10 },
      { ingredientId: 'sugar_syrup', amount: 25 },
      { ingredientId: 'packaging_cup', amount: 1 },
      { ingredientId: 'packaging_straw', amount: 1 },
    ],
  },
  {
    id: 'm_oi_hong',
    name: 'Trà Ổi Hồng',
    price: 18000,
    category: 'Trà Trái Cây Nhiệt Đới',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=400',
    description: 'Hương vị nhiệt đới ngọt ngào nổi bật tự nhiên từ chiết xuất quả ổi hồng dẻo thanh thanh lôi cuốn.',
    available: true,
    recipe: [
      { ingredientId: 'tea_oolong', amount: 10 },
      { ingredientId: 'fresh_fruit_guava', amount: 50 },
      { ingredientId: 'sugar_syrup', amount: 20 },
      { ingredientId: 'packaging_cup', amount: 1 },
      { ingredientId: 'packaging_straw', amount: 1 },
    ],
  },
  {
    id: 'm_xoai_nhietdoi',
    name: 'Trà Xoài Nhiệt Đới',
    price: 18000,
    category: 'Trà Trái Cây Nhiệt Đới',
    imageUrl: 'https://images.unsplash.com/photo-1497534446932-c925b458314e?auto=format&fit=crop&q=80&w=400',
    description: 'Xoài cát tươi thơm bùi ngập tràn sức sống phối cùng oolong chắt lọc tinh hoa mát lành.',
    available: true,
    recipe: [
      { ingredientId: 'tea_oolong', amount: 10 },
      { ingredientId: 'fresh_fruit_mango', amount: 50 },
      { ingredientId: 'sugar_syrup', amount: 20 },
      { ingredientId: 'packaging_cup', amount: 1 },
      { ingredientId: 'packaging_straw', amount: 1 },
    ],
  },
  {
    id: 'm_dua_nhietdoi',
    name: 'Trà Dứa Nhiệt Đới',
    price: 18000,
    category: 'Trà Trái Cây Nhiệt Đới',
    imageUrl: 'https://images.unsplash.com/photo-1546173152-318ae14d43e4?auto=format&fit=crop&q=80&w=400',
    description: 'Thơm (dứa) mật dạt dào bừng sáng hương vị nhiệt đới chua dòn sảng khoái.',
    available: true,
    recipe: [
      { ingredientId: 'tea_oolong', amount: 10 },
      { ingredientId: 'fresh_fruit_pineapple', amount: 55 },
      { ingredientId: 'sugar_syrup', amount: 20 },
      { ingredientId: 'packaging_cup', amount: 1 },
      { ingredientId: 'packaging_straw', amount: 1 },
    ],
  },
  {
    id: 'm_chanhday',
    name: 'Trà Chanh Dây',
    price: 15000,
    category: 'Trà Trái Cây Nhiệt Đới',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=400',
    description: 'Trà giải khát chuẩn gu mộc mạc ngon bùng nổ nhờ vị chua thanh rực rỡ của nước cốt chanh dây chín cây.',
    available: true,
    recipe: [
      { ingredientId: 'tea_oolong', amount: 10 },
      { ingredientId: 'fresh_fruit_passion', amount: 45 },
      { ingredientId: 'sugar_syrup', amount: 25 },
      { ingredientId: 'packaging_cup', amount: 1 },
      { ingredientId: 'packaging_straw', amount: 1 },
    ],
  },

  // --- NHÓM 3: TRÀ SỮA / TRÀ SỮA TRÁI CÂY (Milk Tea / Fruit Milk Tea) ---
  {
    id: 'm_sua_truyenthong',
    name: 'Trà Sữa Truyền Thống',
    price: 15000,
    category: 'Trà Sữa / Trà Sữa Trái Cây',
    imageUrl: 'https://images.unsplash.com/photo-1541658016709-82535e94bc69?auto=format&fit=crop&q=80&w=400',
    description: 'Trà sữa đậm vị hồng trà bí truyền pha chế kết hợp kem béo Đài Loan mịn ngậy đắm chìm mọi giác quan.',
    available: true,
    recipe: [
      { ingredientId: 'tea_black', amount: 15 },
      { ingredientId: 'milk_powder', amount: 35 },
      { ingredientId: 'sugar_syrup', amount: 30 },
      { ingredientId: 'packaging_cup', amount: 1 },
      { ingredientId: 'packaging_straw', amount: 1 },
    ],
  },
  {
    id: 'm_sua_thaixanh',
    name: 'Trà Sữa Thái Xanh',
    price: 18000,
    category: 'Trà Sữa / Trà Sữa Trái Cây',
    imageUrl: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&q=80&w=400',
    description: 'Màu xanh lục mát lạnh mang hương thảo mộc trà Thái đặc trưng ngây ngất béo ngậy.',
    available: true,
    recipe: [
      { ingredientId: 'tea_thai', amount: 15 },
      { ingredientId: 'milk_powder', amount: 30 },
      { ingredientId: 'sugar_syrup', amount: 25 },
      { ingredientId: 'packaging_cup', amount: 1 },
      { ingredientId: 'packaging_straw', amount: 1 },
    ],
  },
  {
    id: 'm_sua_olong',
    name: 'Trà Sữa Olong',
    price: 18500,
    category: 'Trà Sữa / Trà Sữa Trái Cây',
    imageUrl: 'https://images.unsplash.com/photo-1507133750040-4a8f57021571?auto=format&fit=crop&q=80&w=400',
    description: 'Sự kết kết xuất sắc từ trà Oolong nguyên lá sấy thơm chát hậu quyện lớp sữa mịn thanh tao.',
    available: true,
    recipe: [
      { ingredientId: 'tea_oolong', amount: 15 },
      { ingredientId: 'milk_powder', amount: 32 },
      { ingredientId: 'sugar_syrup', amount: 25 },
      { ingredientId: 'packaging_cup', amount: 1 },
      { ingredientId: 'packaging_straw', amount: 1 },
    ],
  },
  {
    id: 'm_sua_matcha',
    name: 'Trà Sữa Matcha',
    price: 20000,
    category: 'Trà Sữa / Trà Sữa Trái Cây',
    imageUrl: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&q=80&w=400',
    description: 'Bột trà matcha Uji Thượng Hạng Nhật Bản đậm đà, béo bùi say đắm, tăng cường collagen tự nhiên.',
    available: true,
    recipe: [
      { ingredientId: 'tea_matcha', amount: 10 },
      { ingredientId: 'milk_powder', amount: 30 },
      { ingredientId: 'sugar_syrup', amount: 25 },
      { ingredientId: 'packaging_cup', amount: 1 },
      { ingredientId: 'packaging_straw', amount: 1 },
    ],
  },
  {
    id: 'm_sua_dau',
    name: 'Trà Sữa Dâu',
    price: 20000,
    category: 'Trà Sữa / Trà Sữa Trái Cây',
    imageUrl: 'https://images.unsplash.com/photo-1546173152-318ae14d43e4?auto=format&fit=crop&q=80&w=400',
    description: 'Ly trà sữa dâu hồng ngọt ngào, thơm lung dâu tây ngọt lim siêu mịn say đắm.',
    available: true,
    recipe: [
      { ingredientId: 'tea_black', amount: 10 },
      { ingredientId: 'milk_powder', amount: 30 },
      { ingredientId: 'sugar_syrup', amount: 20 },
      { ingredientId: 'packaging_cup', amount: 1 },
      { ingredientId: 'packaging_straw', amount: 1 },
    ],
  },
  {
    id: 'm_sua_dao',
    name: 'Trà Sữa Đào',
    price: 20000,
    category: 'Trà Sữa / Trà Sữa Trái Cây',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=400',
    description: 'Mùi quả đào vàng thơm lựng quyến rũ kết hợp hoàn mỹ cùng cốt sữa béo ngậy chuẩn vị.',
    available: true,
    recipe: [
      { ingredientId: 'tea_black', amount: 10 },
      { ingredientId: 'milk_powder', amount: 30 },
      { ingredientId: 'sugar_syrup', amount: 20 },
      { ingredientId: 'packaging_cup', amount: 1 },
      { ingredientId: 'packaging_straw', amount: 1 },
    ],
  },
];

export const INITIAL_CUSTOMERS: CustomerAccount[] = [
  {
    phone: '0933387547',
    name: 'Chủ Quán BobaTea',
    email: 'teamleader.hc2019@gmail.com',
    points: 250, // Vàng
    tier: MembershipTier.GOLD,
    totalSpent: 2500000,
    createdAt: '2026-05-01T08:30:00Z',
  },
  {
    phone: '0987654321',
    name: 'Nguyễn Văn Anh',
    email: 'vananh@gmail.com',
    points: 320, // Hạng Vàng
    tier: MembershipTier.GOLD,
    totalSpent: 3200000,
    createdAt: '2026-01-10T08:30:00Z',
  },
  {
    phone: '0912345678',
    name: 'Trần Thị Bình',
    email: 'binhtran@gmail.com',
    points: 580, // Hạng Kim Cương
    tier: MembershipTier.PLATINUM,
    totalSpent: 5800000,
    createdAt: '2026-02-15T09:15:00Z',
  },
  {
    phone: '0933445566',
    name: 'Phạm Minh Cường',
    email: 'cuongpham@gmail.com',
    points: 45, // Hạng Đồng
    tier: MembershipTier.BRONZE,
    totalSpent: 450000,
    createdAt: '2026-05-12T14:20:00Z',
  },
];

export const INITIAL_PROMOTIONS: PromotionNotification[] = [
  {
    id: 'promo_MUA2TANG1',
    title: '🎉 Chương Trình MUA 2 TẶNG 1 Siêu Hot',
    content: 'Chương trình ưu đãi cực khủng: Mua 2 ly nước bất kỳ tặng ngay 1 ly nước giá trị bằng hoặc thấp nhất hoàn toàn miễn phí! Đặt ngay hôm nay.',
    code: 'MUA2TANG1',
    discountPercent: 33, // giảm tương đương 1/3 cho combo 3 ly
    active: true,
    expiryDate: '2026-06-30T23:59:59Z',
  },
  {
    id: 'promo_HE2026',
    title: '☀️ Chào Hè Rực Rỡ - Giảm Ngay 15k',
    content: 'Những ngày nắng rực rỡ, giải nhiệt ngay với trà trái cây tươi ngon mỗi ngày từ nông trại. Nhập mã HE2026 để giảm 15% tổng đơn đặt hàng.',
    code: 'HE2026',
    discountPercent: 15,
    active: true,
    expiryDate: '2026-06-30T23:59:59Z',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ORD-20260524-1024',
    customerPhone: '0933387547',
    customerName: 'Chủ Quán BobaTea',
    items: [
      {
        id: 'ord_line_1',
        menuItemId: 'm_xoai_chanhday',
        name: 'Trà Xoài + Chanh Dây',
        price: 20000,
        quantity: 2,
        sweetness: 70,
        ice: 50,
        toppings: [],
      },
    ],
    subtotal: 40000,
    discount: 2000, // Gold discount 5%
    total: 38050,
    paymentMethod: PaymentMethod.ONLINE_QR,
    paymentStatus: PaymentStatus.PAID,
    status: OrderStatus.COMPLETED,
    pointsEarned: 4,
    createdAt: '2026-05-24T03:15:00Z',
    rolePlaced: UserRole.CUSTOMER,
  },
  {
    id: 'ORD-20260524-1023',
    customerPhone: undefined,
    items: [
      {
        id: 'ord_line_2',
        menuItemId: 'm_vai_thanhlong',
        name: 'Trà Vải Thanh Long',
        price: 20000,
        quantity: 1,
        sweetness: 100,
        ice: 70,
        toppings: [],
      },
    ],
    subtotal: 20000,
    discount: 0,
    total: 20000,
    paymentMethod: PaymentMethod.CASH,
    paymentStatus: PaymentStatus.PAID,
    status: OrderStatus.COMPLETED,
    pointsEarned: 0,
    createdAt: '2026-05-24T03:08:00Z',
    rolePlaced: UserRole.STAFF,
  },
];
